services:
  - type: worker
    name: telegram-gemini-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python сигмоида.py
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false

